repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
     -  id: mypy
        files: sklearn_pytorch_engine/
        additional_dependencies: [pytest==6.2.4]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: sklearn_pytorch_engine/
